"""empty message

迁移 ID: c193ecebf158
父迁移: 
创建时间: 2025-09-16 15:53:00.953711

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c193ecebf158'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('word_bank_qa',)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_bank_qa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='群聊ID'),
    sa.Column('question', sa.String(length=500), nullable=False, comment='问题'),
    sa.Column('answer', sa.Text(), nullable=False, comment='答案'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_word_bank_qa')),
    info={'bind_key': 'word_bank_qa'}
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_bank_qa')
    # ### end Alembic commands ###
